version: '3'

services:
  database:
    container_name: mariadbDB
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: todoProject
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Dockerfile:/build/app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadbDB:3306/todoProject?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - database
    networks:
      - test_network


networks:
  test_network: